### ISSUE TITLE
Allow git commit command to be run with `--no-verify`

### ISSUE THREAD

**Issue by attack** [lpender/bummr#49]
Thanks for the great work.

I would love to use this for my project.  However, we use git workflow hooks for `pre-commit`.  One of our hooks will check the format of the commit message. The standard `bummr` commit message fails this check and rejects the commit.

This can easily be avoided by skipping any `pre-commit` hooks:
`git commit -am 'message' --no-verify`.

I can create a PR with a change that allows this, but I just wanted to gauge whether this would be accepted?  I think I would follow your previous use of `ENV` vars (ie `BUMMR_TEST` and `BASE_BRANCH`).

**Comment by lpender** [comment]
Thanks @attack

An environment variable does seem like a better option than a command line flag, since I assume this is something that will always be associated with the branch.

That sounds like it could be useful for people, if you feel inspired to open a PR, go ahead! I will take a look at it with an eye towards getting it merged.
